services:
  kong-db:
    image: postgres:16
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - C:/Abhinay/Code/Kong/kong-hybrid/data/postgres:/var/lib/postgresql/data
    networks:
      - kong-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
      interval: 5s
      timeout: 5s
      retries: 20

  kong-cp:
    image: kong:latest
    container_name: kong-cp
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong

      KONG_ROLE: control_plane
      KONG_CLUSTER_LISTEN: 0.0.0.0:8005
      KONG_CLUSTER_CERT: /certs/cluster.crt
      KONG_CLUSTER_CERT_KEY: /certs/cluster.key

      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - C:/Abhinay/Code/Kong/kong-hybrid/certs:/certs
    ports:
      - "8001:8001"
      - "8005:8005"
    depends_on:
      kong-db:
        condition: service_healthy
    networks:
      - kong-net

  kong-dp:
    image: kong:latest
    container_name: kong-dp
    environment:
      KONG_DATABASE: "off"

      KONG_ROLE: data_plane
      KONG_CLUSTER_CONTROL_PLANE: kong-cp:8005
      KONG_CLUSTER_CERT: /certs/cluster.crt
      KONG_CLUSTER_CERT_KEY: /certs/cluster.key

      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - C:/Abhinay/Code/Kong/kong-hybrid/certs:/certs
    ports:
      - "8000:8000"
    depends_on:
      - kong-cp
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge